all:
  hosts:
    10.222.222.70:
      ansible_become: yes
  vars:
    artifactory_url: http://artifactory.infinnity.ru
    registry_host: artifactory.infinnity.ru/docker/docker/edu-docker
    registry_user: e.ishemgulova
    registry_pass: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      373....3665
    project_dir: /opt/my_app

    python_image_name: "ishemgulova_python"
    python_image_tag: "1.1.3"
    python_app_dir: "python"

    java_image_name: "ishemgulova_java"
    java_image_tag: "1.5.1"
    java_app_dir: "java"
